#!/usr/bin/env python3
"""Insert a generated release section into .github/CHANGELOG.md.

Usage: update_changelog.py <version> <generated-file> <changelog-file>

The generated file holds the label-grouped list of pull requests produced by
release-changelog-builder-action. It is turned into a section

    # Version  <version>

    #### <group>

    * [#<number>](<url>): <title>

and inserted at the top of the changelog. Group headings without any entries
below them are dropped, so an empty "Other Changes" group does not leave a
dangling heading behind. The rest of the changelog is left exactly as it is.

If the changelog already has a section for the version, it is left untouched,
so maintainers can reword the generated entries without a later run
overwriting them.

The generated file is rewritten to hold the pull request comment body: the new
section, or, when the section already existed, a note followed by the freshly
generated list for reference.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# The header keeps the two spaces used by earlier releases in CHANGELOG.md.
HEADER_PREFIX = "# Version  "
SECTION_RE = re.compile(r"^#\s+Version\s+(?P<version>\S+)\s*$")
GROUP_RE = re.compile(r"^#{2,6}\s")
NO_ENTRIES_PLACEHOLDER = "* No changelog entries for this release."


def normalise_version(version: str) -> str:
    """Normalises a version string so tag names and changelog headers compare equal.

    Args:
        version (str): A version as written in a tag, title or header, e.g. "v0.3.0" or " 0.3.0RC1".

    Returns:
        str: The version without surrounding whitespace or a leading "v", in lower case, e.g. "0.3.0rc1".
    """
    return version.strip().lstrip("vV").lower()


def tidy(text: str) -> str:
    """Tidies generated Markdown by trimming trailing whitespace and collapsing runs of blank lines.

    Only applied to text generated by the action, never to the existing changelog, whose formatting (e.g. hard line
    breaks written as two trailing spaces) must be kept.

    Args:
        text (str): The Markdown text to tidy.

    Returns:
        str: The tidied text, without leading or trailing blank lines.
    """
    collapsed: list[str] = []
    for line in (line.rstrip() for line in text.splitlines()):
        if not line and collapsed and not collapsed[-1]:
            continue
        collapsed.append(line)
    return "\n".join(collapsed).strip("\n")


def drop_empty_groups(text: str) -> str:
    """Removes group headings, such as "#### Bug Fixes", that have no entries below them.

    Args:
        text (str): The label-grouped Markdown generated by release-changelog-builder-action.

    Returns:
        str: The tidied Markdown with only the groups that list at least one entry. Empty if no group has any.
    """
    lines = text.splitlines()
    kept: list[str] = []
    index = 0
    while index < len(lines):
        if GROUP_RE.match(lines[index]):
            end = index + 1
            while end < len(lines) and not GROUP_RE.match(lines[end]):
                end += 1
            if any(line.strip() for line in lines[index + 1 : end]):
                kept.extend(lines[index:end])
            index = end
        else:
            kept.append(lines[index])
            index += 1
    return tidy("\n".join(kept))


def has_section(changelog: str, version: str) -> bool:
    """Checks whether the changelog already has a section for a version.

    Args:
        changelog (str): The content of the changelog file.
        version (str): The normalised version to look for, e.g. "0.3.0".

    Returns:
        bool: True if a "# Version <version>" header exists, with any spacing or leading "v", else False.
    """
    for line in changelog.splitlines():
        match = SECTION_RE.match(line)
        if match and normalise_version(match.group("version")) == version:
            return True
    return False


def insert_section(changelog: str, section: str) -> str:
    """Inserts a release section at the top of the changelog, leaving the rest of it exactly as it is.

    Args:
        changelog (str): The content of the changelog file. May be empty.
        section (str): The release section to insert, starting with its "# Version" header.

    Returns:
        str: The updated changelog, ending with a newline.
    """
    rest = changelog.lstrip("\n")
    if not rest:
        return section + "\n"
    return f"{section}\n\n{rest}"


def main() -> int:
    """Runs the command-line interface: inserts the generated section and writes the pull request comment body.

    Reads the version, the generated file and the changelog file from the command line (see the module docstring).

    Returns:
        int: The exit code, 0 on success or 1 if the generated file is missing.
    """
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("version", help="release version, e.g. 0.3.0 or 0.3.0rc1")
    parser.add_argument("generated", type=Path, help="changelog built by the action")
    parser.add_argument("changelog", type=Path, help="changelog file to update")
    args = parser.parse_args()

    if not args.generated.is_file():
        sys.stderr.write(f"error: {args.generated} was not generated\n")
        return 1

    # An empty body means every entry was filtered out, e.g. by ignore_labels.
    # The action itself renders "empty_template" when no pull requests exist.
    body = drop_empty_groups(args.generated.read_text(encoding="utf-8")) or NO_ENTRIES_PLACEHOLDER

    version = normalise_version(args.version)
    section = f"{HEADER_PREFIX}{version}\n\n{body}"
    existing = args.changelog.read_text(encoding="utf-8") if args.changelog.is_file() else ""

    if has_section(existing, version):
        comment = (
            f"`{args.changelog.as_posix()}` already has a section for version {version}, so it was left "
            "unchanged to keep any manual edits. The freshly generated list is below for reference; "
            "copy anything missing by hand.\n\n"
            f"{section}\n"
        )
        sys.stdout.write(f"{args.changelog} already has version {version}, left unchanged\n")
    else:
        args.changelog.write_text(insert_section(existing, section), encoding="utf-8", newline="\n")
        comment = f"{section}\n"
        sys.stdout.write(f"updated {args.changelog} for version {version}\n")

    # Reuse the generated file as the pull request comment body.
    args.generated.write_text(comment, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
