SOLVER:
  BATCH_SIZE: 32
  MAX_EPOCH: 2
  LR: 1e-4
  DA_LR: 5e-5
  SEED: 42

DA:
  TASK: True
  USE: True
  METHOD: "CDAN"
  USE_ENTROPY: False
  RANDOM_LAYER: True
  ORIGINAL_RANDOM: True
  RANDOM_DIM: 256
  INIT_EPOCH: 10

DECODER:
  BINARY: 2

COMET:
  EXPERIMENT_NAME: "DrugBAN_DA"
