DATASET:
 TRAIN: 'data/fine_tune/train_data.json'
 VAL: 'data/fine_tune/test_data.json'

MODEL:
  NAME: "cgcnn"
  PRETRAINED_MODEL_PATH: " " # NOT EXIST
  INIT_FILE: 'cif_file/atom_init.json'
  CIF_FOLDER: "cif_file"

SOLVER:
  LR: 0.01
  EPOCHS: 1


LOGGING:
  LOG_DIR: "saved_models"
  LOG_DIR_NAME: "cgcnn"
