# This is a demo config file for protonet.
# Users can modify the dataset and output paths to train their own model.
# For more adjustable hyperparameters, please refer to template.yaml.
DATASET:
  ROOT: "data/omniglot"
OUTPUT:
  OUT_DIR: "outputs"
  LOG_DIR: "logs"
  WEIGHT_DIR: "weights"
