# This workflow will control the stale and close of prs and issues.
# For more information see: https://github.com/actions/stale

name: stale

on:
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron:  '0 0 * * *' # every midnight

jobs:
  stale:
    name: Mark (and close) stale issues and pull requests
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 30   # Mark an issue as stale if there has been no activity for 30 days.
          days-before-issue-close: -1   # Do not automatically close stale issues (-1 disables auto-closing).
          days-before-pr-stale: 45      # Mark a pull request as stale if there has been no activity for 45 days.
          days-before-pr-close: -1      # Do not automatically close stale pull requests (-1 disables auto-closing).
          stale-issue-message: "This issue has been automatically marked as stale due to lack of activity."
          stale-pr-message: "This pull request has been automatically marked as stale due to lack of activity."
          stale-issue-label: "stale-issue"
          exempt-issue-labels: "bug, enhancement, new feature"
